  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: I050368-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: I050368-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-eu01
    integrationFlowId: I050368-flow4
    integrationFlowName: I050368-flow4
    packageId: CICD
    filePath: I050368-flow4.zip
